from prometheus_client import Counter, Histogram, Gauge

# Context window size (128K for gemma4:e2b)
CONTEXT_WINDOW_SIZE = 131072

# LLM request duration
llm_request_duration = Histogram(
    "llm_request_duration_seconds",
    "Time spent generating LLM responses",
    labelnames=["model"],
    buckets=[0.5, 1, 2, 5, 10, 20, 30, 60, 120, 300],
)

# Total LLM requests
llm_requests_total = Counter(
    "llm_requests_total",
    "Total number of LLM requests",
    labelnames=["model", "status"],
)

# Input tokens
llm_tokens_input = Counter(
    "llm_tokens_input_total",
    "Total input tokens sent to LLM",
    labelnames=["model"],
)

# Output tokens
llm_tokens_output = Counter(
    "llm_tokens_output_total",
    "Total output tokens generated by LLM",
    labelnames=["model"],
)

# Context window usage (last request)
llm_context_usage = Gauge(
    "llm_context_tokens_used",
    "Tokens used in context window (last request)",
    labelnames=["model"],
)

# Context window percentage
llm_context_usage_ratio = Gauge(
    "llm_context_usage_ratio",
    "Ratio of context window used (0-1)",
    labelnames=["model"],
)

# Context window total size
llm_context_window_size = Gauge(
    "llm_context_window_size",
    "Total context window size in tokens",
    labelnames=["model"],
)

# LLM errors
llm_errors_total = Counter(
    "llm_errors_total",
    "Total LLM errors",
    labelnames=["model"],
)
